// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37aV1ePHBaZ_htDeWsmX1FSSrNWu2KaI',
    appId: '1:784873463457:web:ee2ac3d85f6fe22ac91ae0',
    messagingSenderId: '784873463457',
    projectId: 'tajgo-4fcd0',
    authDomain: 'tajgo-4fcd0.firebaseapp.com',
    databaseURL: 'https://tajgo-4fcd0-default-rtdb.firebaseio.com',
    storageBucket: 'tajgo-4fcd0.firebasestorage.app',
    measurementId: 'G-EVYQZXGTEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Qi01lHFXKit8X9tVz7ghxs_N4um4UxE',
    appId: '1:784873463457:android:33da27eafa9432a4c91ae0',
    messagingSenderId: '784873463457',
    projectId: 'tajgo-4fcd0',
    databaseURL: 'https://tajgo-4fcd0-default-rtdb.firebaseio.com',
    storageBucket: 'tajgo-4fcd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwHjbFV-Jg88vYHvB0AAn75cZpW0Xp2s',
    appId: '1:784873463457:ios:42381eb986ce1b77c91ae0',
    messagingSenderId: '784873463457',
    projectId: 'tajgo-4fcd0',
    databaseURL: 'https://tajgo-4fcd0-default-rtdb.firebaseio.com',
    storageBucket: 'tajgo-4fcd0.firebasestorage.app',
    iosBundleId: 'com.example.tajgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwHjbFV-Jg88vYHvB0AAn75cZpW0Xp2s',
    appId: '1:784873463457:ios:42381eb986ce1b77c91ae0',
    messagingSenderId: '784873463457',
    projectId: 'tajgo-4fcd0',
    databaseURL: 'https://tajgo-4fcd0-default-rtdb.firebaseio.com',
    storageBucket: 'tajgo-4fcd0.firebasestorage.app',
    iosBundleId: 'com.example.tajgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA37aV1ePHBaZ_htDeWsmX1FSSrNWu2KaI',
    appId: '1:784873463457:web:cab93b24fc11e9d1c91ae0',
    messagingSenderId: '784873463457',
    projectId: 'tajgo-4fcd0',
    authDomain: 'tajgo-4fcd0.firebaseapp.com',
    databaseURL: 'https://tajgo-4fcd0-default-rtdb.firebaseio.com',
    storageBucket: 'tajgo-4fcd0.firebasestorage.app',
    measurementId: 'G-V85TFYB127',
  );
}
