import 'package:cloud_firestore/cloud_firestore.dart';

import 'marketplace_partner.dart';
import 'marketplace_product.dart';

const marketplaceSamplePartners = <MarketplacePartner>[
  MarketplacePartner(
    id: 'sample-tajgo-kitchen',
    name: 'Пример · TajGo Kitchen',
    category: 'food',
    description: 'Горячие блюда и быстрые обеды',
    address: 'проспект Исмоили Сомони, Худжанд',
    location: GeoPoint(40.2833, 69.6222),
    minimumOrder: 30,
    deliveryFee: 12,
    rating: 4.9,
    preparationMinutes: 25,
    workingHours: '09:00–22:00',
    isTest: true,
    isPreview: true,
  ),
  MarketplacePartner(
    id: 'sample-oshi-khujand',
    name: 'Пример · Оши Хуҷанд',
    category: 'food',
    description: 'Плов, самбӯса и домашняя кухня',
    address: 'улица Камоли Худжанди, Худжанд',
    location: GeoPoint(40.2861, 69.6194),
    minimumOrder: 35,
    deliveryFee: 11,
    rating: 4.8,
    preparationMinutes: 30,
    workingHours: '10:00–21:30',
    isTest: true,
    isPreview: true,
  ),
  MarketplacePartner(
    id: 'sample-sabzavot-market',
    name: 'Пример · Сабзавот Маркет',
    category: 'groceries',
    description: 'Свежие продукты на каждый день',
    address: '18-й микрорайон, Худжанд',
    location: GeoPoint(40.2874, 69.6184),
    minimumOrder: 25,
    deliveryFee: 10,
    rating: 4.8,
    preparationMinutes: 15,
    workingHours: '08:00–21:00',
    isTest: true,
    isPreview: true,
  ),
  MarketplacePartner(
    id: 'sample-bozori-somon',
    name: 'Пример · Бозори Сомон',
    category: 'groceries',
    description: 'Овощи, фрукты и товары первой необходимости',
    address: 'улица Гагарина, Худжанд',
    location: GeoPoint(40.2912, 69.6301),
    minimumOrder: 40,
    deliveryFee: 13,
    rating: 4.7,
    preparationMinutes: 20,
    workingHours: '07:30–20:30',
    isTest: true,
    isPreview: true,
  ),
  MarketplacePartner(
    id: 'sample-gulhoi-sughd',
    name: 'Пример · Гулҳои Суғд',
    category: 'flowers',
    description: 'Букеты и цветы с доставкой по городу',
    address: 'улица Рахмон Набиев, Худжанд',
    location: GeoPoint(40.2798, 69.6268),
    minimumOrder: 50,
    deliveryFee: 15,
    rating: 5,
    preparationMinutes: 20,
    workingHours: '08:00–23:00',
    isTest: true,
    isPreview: true,
  ),
  MarketplacePartner(
    id: 'sample-florist-khujand',
    name: 'Пример · Florist Khujand',
    category: 'flowers',
    description: 'Современные букеты и подарочная упаковка',
    address: 'проспект Рахмон Набиев, Худжанд',
    location: GeoPoint(40.2816, 69.6149),
    minimumOrder: 60,
    deliveryFee: 14,
    rating: 4.9,
    preparationMinutes: 25,
    workingHours: '09:00–22:00',
    isTest: true,
    isPreview: true,
  ),
];

const marketplaceSampleProducts = <MarketplaceProduct>[
  MarketplaceProduct(
    id: 'sample-kitchen-plov',
    partnerId: 'sample-tajgo-kitchen',
    name: 'Оши палав',
    description: 'Порция традиционного плова',
    price: 32,
    unit: 'portion',
    popularity: 100,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-kitchen-qurutob',
    partnerId: 'sample-tajgo-kitchen',
    name: 'Қурутоб',
    description: 'Классическая порция с зеленью',
    price: 28,
    unit: 'portion',
    popularity: 90,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-kitchen-salad',
    partnerId: 'sample-tajgo-kitchen',
    name: 'Салат свежий',
    description: 'Огурцы, помидоры и зелень',
    price: 14,
    unit: 'portion',
    popularity: 70,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-oshi-sambusa',
    partnerId: 'sample-oshi-khujand',
    name: 'Самбӯса',
    description: 'Самса из тандыра',
    price: 8,
    unit: 'item',
    popularity: 100,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-oshi-shurbo',
    partnerId: 'sample-oshi-khujand',
    name: 'Шӯрбо',
    description: 'Домашний суп с мясом и овощами',
    price: 24,
    unit: 'portion',
    popularity: 80,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-oshi-tea',
    partnerId: 'sample-oshi-khujand',
    name: 'Чойи кабуд',
    description: 'Зелёный чай, чайник',
    price: 10,
    unit: 'item',
    popularity: 60,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-market-apples',
    partnerId: 'sample-sabzavot-market',
    name: 'Яблоки',
    description: 'Свежие яблоки местного урожая',
    price: 12,
    unit: 'kg',
    popularity: 90,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-market-tomatoes',
    partnerId: 'sample-sabzavot-market',
    name: 'Помидоры',
    description: 'Спелые помидоры',
    price: 10,
    unit: 'kg',
    popularity: 85,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-market-bread',
    partnerId: 'sample-sabzavot-market',
    name: 'Лепёшка',
    description: 'Свежий хлеб из тандыра',
    price: 4,
    unit: 'item',
    popularity: 100,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-bozor-bananas',
    partnerId: 'sample-bozori-somon',
    name: 'Бананы',
    description: 'Спелые бананы',
    price: 18,
    unit: 'kg',
    popularity: 90,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-bozor-rice',
    partnerId: 'sample-bozori-somon',
    name: 'Рис',
    description: 'Рис для плова',
    price: 16,
    unit: 'kg',
    popularity: 80,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-bozor-oil',
    partnerId: 'sample-bozori-somon',
    name: 'Масло растительное',
    description: 'Бутылка 1 литр',
    price: 22,
    unit: 'item',
    popularity: 75,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-gulhoi-roses',
    partnerId: 'sample-gulhoi-sughd',
    name: 'Букет роз',
    description: '7 свежих роз',
    price: 85,
    unit: 'bouquet',
    popularity: 100,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-gulhoi-tulips',
    partnerId: 'sample-gulhoi-sughd',
    name: 'Букет тюльпанов',
    description: '9 сезонных тюльпанов',
    price: 65,
    unit: 'bouquet',
    popularity: 85,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-gulhoi-card',
    partnerId: 'sample-gulhoi-sughd',
    name: 'Открытка',
    description: 'Открытка с вашей подписью',
    price: 8,
    unit: 'item',
    popularity: 65,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-florist-mix',
    partnerId: 'sample-florist-khujand',
    name: 'Авторский букет',
    description: 'Сезонный микс в фирменной упаковке',
    price: 110,
    unit: 'bouquet',
    popularity: 100,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-florist-box',
    partnerId: 'sample-florist-khujand',
    name: 'Цветы в коробке',
    description: 'Композиция среднего размера',
    price: 140,
    unit: 'bouquet',
    popularity: 80,
    isTest: true,
  ),
  MarketplaceProduct(
    id: 'sample-florist-ribbon',
    partnerId: 'sample-florist-khujand',
    name: 'Подарочная лента',
    description: 'Дополнительное оформление букета',
    price: 6,
    unit: 'item',
    popularity: 50,
    isTest: true,
  ),
];

List<MarketplacePartner> samplePartnersForCategory(String? category) =>
    marketplaceSamplePartners
        .where((partner) => category == null || partner.category == category)
        .toList(growable: false);

List<MarketplaceProduct> sampleProductsForPartner(String partnerId) =>
    marketplaceSampleProducts
        .where((product) => product.partnerId == partnerId)
        .toList(growable: false);
